# site settings
title: ASHWATTHAMA
subtitle: SANDERS
email: sai404142@gmail.com
description: ANDROID ENTHUSIAST | UX DESIGNER |CUSTOM ROM DEVELOPER
baseurl: "/forty-jekyll-theme" # the subpath of your site, e.g. /blog
url: # the base hostname & protocol for your site
author:
street_address: Alwal Hills
city: Hyderabad
state: TG
zip_code: 500010
country: India
phone: xyz

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 8

# social settings
500px_url:
facebook_url:
gitlab_url:
github_url: https://gitlab.com/u/sai4041412
googleplus_url: https://plus.google.com/u/0/+sai404142
instagram_url: https://instagram.com/saisamy95
linkedin_url: https://www.linkedin.com/in/sai404142
pinterest_url:
slack_url:
twitter_url: https://twitter.com/wittyindiann

# build settings
markdown: kramdown

sass:
  style: compressed
